from pathlib import Path
import base64,re
p=Path("index.html")
s=p.read_text()
# Preserve the approved base application exactly; discard every Page 05 extension.
end=s.find("</body></html>")
if end<0: raise SystemExit("base boundary missing")
base=s[:end+14]
css=r'''<style>
/* PAGE05_CLEAN_V3 */
.p5v3{position:fixed;inset:0;z-index:100;background:#0b1f3a;padding:calc(10px + env(safe-area-inset-top)) 16px calc(14px + env(safe-area-inset-bottom));display:flex;flex-direction:column;color:#101828}.p5v3h{height:62px;display:grid;grid-template-columns:38px 1fr 38px;align-items:center;color:white}.p5v3h button{border:0;background:none;color:white;font-size:32px}.p5v3h div{text-align:center}.p5v3h h2{margin:0;font-size:20px}.p5v3h p{margin:2px 0 0;font-size:10px;color:#b8c6d9}.p5v3b{flex:1;min-height:0;overflow:auto;background:#f5f7fa;border-radius:20px;padding:14px}.p5v3teams,.p5v3grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.p5v3team,.p5v3card{background:white;border:1px solid #e4e7ec;border-radius:14px;padding:12px}.p5v3team b{display:block;color:#155eef;font-size:14px;margin-bottom:6px}.p5v3team strong{display:block;font-size:15px;line-height:21px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.p5v3card{margin-top:12px;border:0;padding:15px}.p5v3card h3{margin:0 0 5px;font-size:17px}.p5v3card p{margin:0 0 12px;color:#667085;font-size:11px;line-height:1.45}.p5v3btn{min-height:52px;border:1px solid #e1e6ee;border-radius:11px;background:#f8fafc;color:#344054;font-weight:800}.p5v3btn.on{border:2px solid #155eef;background:#eef4ff;color:#155eef}.p5v3primary{width:100%;height:52px;margin-top:12px;border:0;border-radius:12px;background:#155eef;color:white;font-size:15px;font-weight:850}.p5v3primary:disabled{background:#cbd5e1}.p5v3result{padding:11px;border-radius:11px;background:#eef4ff;color:#1849a9;text-align:center;font-weight:850;margin:12px 0}
.p5v3coinStage{height:130px;display:grid;place-items:center;perspective:700px}.p5v3coin{width:88px;height:88px;border-radius:50%;display:grid;place-items:center;border:5px solid rgba(255,255,255,.75);box-shadow:inset 0 0 0 3px rgba(0,0,0,.2),0 8px 18px #10182830;color:white;font-size:14px;font-weight:950}.p5v3coin.blue{background:radial-gradient(circle at 32% 25%,#93c5fd,#2563eb 48%,#123a8c)}.p5v3coin.red{background:radial-gradient(circle at 32% 25%,#fca5a5,#dc2626 48%,#7f1d1d)}.p5v3coin.flip{animation:p5v3flip .8s ease-out}@keyframes p5v3flip{0%{transform:rotateY(0) translateY(0)}45%{transform:rotateY(900deg) translateY(-30px)}100%{transform:rotateY(1800deg) translateY(0)}}
.p5v3labels{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:12px 0 6px}.p5v3labels span{text-align:center;font-size:12px;font-weight:900;color:#344054}.p5v3court{position:relative;width:100%;aspect-ratio:2.2/1;background:#159297;border:3px solid #f3ffff;border-radius:10px;overflow:hidden}.p5v3net{position:absolute;left:50%;top:0;bottom:0;width:4px;background:#071725;transform:translateX(-50%)}.p5v3nv{position:absolute;top:0;bottom:0;width:15.91%;background:#0d737777}.p5v3nv.l{right:50%;border-left:2px solid white}.p5v3nv.r{left:50%;border-right:2px solid white}.p5v3mid{position:absolute;top:50%;height:2px;width:34.09%;background:white}.p5v3mid.l{left:0}.p5v3mid.r{right:0}.p5v3p{position:absolute;transform:translate(-50%,-50%);min-width:76px;max-width:105px;padding:6px;border-radius:9px;background:white;text-align:center;font-size:10px;font-weight:850;white-space:nowrap}.p5v3p.server{background:#155eef;color:white}.p5v3p.receiver{outline:3px solid #fdb022}.p5v3ball{position:absolute;width:12px;height:12px;border-radius:50%;background:#ffd21f;border:2px solid white;box-shadow:0 1px 3px #0004;top:50%;transform:translateY(-50%)}.p5v3ball.r{right:-18px}.p5v3ball.l{left:-18px}.p5v3legend{display:flex;justify-content:center;gap:12px;margin-top:10px;color:#667085;font-size:10px}.p5v3dot{display:inline-block;width:8px;height:8px;border-radius:50%;margin-right:4px}.p5v3dot.s{background:#155eef}.p5v3dot.r{background:#fdb022}
</style>'''
base=base.replace("</head>",css+"</head>",1)
js=r'''<script>
(function(){
var app=document.getElementById('app'),saved='',step='method',picked='',face='',winner='',chooser='',serveTeam='',endTeam='',endSide='left',order={A:[0,1],B:[0,1]},deferred='',startA=0,startB=0;
function esc(x){return String(x||'').replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function other(t){return t==='A'?'B':'A'}
function players(){var d=document.createElement('div');d.innerHTML=saved;function v(id,f){var e=d.querySelector('#'+id);return esc(e&&e.value?e.value:f)}return{A:[v('a1','VĐV A1'),v('a2','VĐV A2')],B:[v('b1','VĐV B1'),v('b2','VĐV B2')]}}
function teamCards(x,y){var p=players();x=x||'A';y=y||'B';function one(t){return'<div class="p5v3team"><b>ĐỘI '+t+'</b><strong>'+p[t][0]+'</strong><strong>'+p[t][1]+'</strong></div>'}return'<div class="p5v3teams">'+one(x)+one(y)+'</div>'}
function shell(body,x,y){app.innerHTML='<main class="p5v3"><header class="p5v3h"><button data-p5="back">‹</button><div><h2>Chuẩn bị trận</h2><p>Theo luật USA Pickleball 2026</p></div><span></span></header><div class="p5v3b">'+teamCards(x,y)+body+'</div></main>'}
function choice(t,deferOK){return'<section class="p5v3card"><h3>Đội '+t+' chọn quyền</h3><p>Chọn một quyền theo thủ tục trước trận.</p><div class="p5v3grid"><button class="p5v3btn" data-p5="serve">Giao bóng</button><button class="p5v3btn" data-p5="receive">Nhận bóng</button><button class="p5v3btn" data-p5="end">Chọn bên sân</button>'+(deferOK?'<button class="p5v3btn" data-p5="defer">Nhường quyền chọn</button>':'')+'</div></section>'}
function draw(){
 if(step==='method')return shell('<section class="p5v3card"><h3>Xác định quyền trước trận</h3><p>Chọn phương pháp xác định quyền đầu tiên.</p><div class="p5v3grid"><button class="p5v3btn" data-p5="toss">Tung đồng xu</button><button class="p5v3btn" data-p5="known">Đã xác định</button></div></section>');
 if(step==='pick')return shell('<section class="p5v3card"><h3>Tung đồng xu</h3><p>Chọn đội gọi mặt XANH. Đội còn lại là ĐỎ.</p><div class="p5v3coinStage"><div class="p5v3coin blue">XANH</div></div><div class="p5v3grid"><button class="p5v3btn '+(picked==='A'?'on':'')+'" data-p5="pickA">Đội A gọi XANH</button><button class="p5v3btn '+(picked==='B'?'on':'')+'" data-p5="pickB">Đội B gọi XANH</button></div><button class="p5v3primary" data-p5="flip" '+(!picked?'disabled':'')+'>Tung đồng xu</button></section>');
 if(step==='result')return shell('<section class="p5v3card"><h3>Kết quả</h3><div class="p5v3coinStage"><div class="p5v3coin '+(face==='XANH'?'blue':'red')+' flip">'+face+'</div></div><div class="p5v3result">Đội '+winner+' thắng quyền chọn đầu tiên</div></section>'+choice(winner,true));
 if(step==='known')return shell('<section class="p5v3card"><h3>Đội có quyền chọn đầu tiên</h3><div class="p5v3grid"><button class="p5v3btn" data-p5="knownA">Đội A</button><button class="p5v3btn" data-p5="knownB">Đội B</button></div></section>');
 if(step==='deferred')return shell('<div class="p5v3result">Đội '+deferred+' nhường quyền chọn</div>'+choice(chooser,false));
 if(step==='second')return shell('<div class="p5v3result">Đội '+endTeam+' chọn bên sân</div><section class="p5v3card"><h3>Đội '+chooser+' chọn giao hay nhận</h3><div class="p5v3grid"><button class="p5v3btn" data-p5="serve">Giao bóng</button><button class="p5v3btn" data-p5="receive">Nhận bóng</button></div></section>');
 if(step==='side')return shell('<div class="p5v3result">Đội '+serveTeam+' giao bóng đầu tiên</div><section class="p5v3card"><h3>Đội '+endTeam+' chọn bên sân</h3><p>Theo góc nhìn của trọng tài.</p><div class="p5v3grid"><button class="p5v3btn '+(endSide==='left'?'on':'')+'" data-p5="left">Bên trái</button><button class="p5v3btn '+(endSide==='right'?'on':'')+'" data-p5="right">Bên phải</button></div><button class="p5v3primary" data-p5="positions">Tiếp tục</button></section>');
 if(step==='positions')return positions()
}
function resolve(k){var t=chooser;if(k==='defer'){deferred=t;chooser=other(t);step='deferred';return draw()}if(k==='serve'||k==='receive'){serveTeam=k==='serve'?t:other(t);endTeam=other(t);step='side';return draw()}if(k==='end'){endTeam=t;chooser=other(t);step='second';return draw()}}
function positions(){
 var p=players(),leftTeam=endSide==='left'?endTeam:other(endTeam),rightTeam=other(leftTeam),recvTeam=other(serveTeam);
 var serveEven=(serveTeam==='A'?startA:startB)%2===0,recvEven=(recvTeam==='A'?startA:startB)%2===0;
 var ss=serveTeam===leftTeam?(serveEven?1:0):(serveEven?0:1),rs=recvTeam===leftTeam?(recvEven?1:0):(recvEven?0:1);
 function name(t,k){return p[t][order[t][k]]}function pos(t,k){return'left:'+(t===leftTeam?'16':'84')+'%;top:'+(k===0?'28':'72')+'%'}function cls(t,k){return t===serveTeam&&k===ss?' server':(t===recvTeam&&k===rs?' receiver':'')}function ball(t,k){return t===serveTeam&&k===ss?'<i class="p5v3ball '+(t===leftTeam?'r':'l')+'"></i>':''}
 var court='<div class="p5v3labels"><span>ĐỘI '+leftTeam+'</span><span>ĐỘI '+rightTeam+'</span></div><div class="p5v3court"><div class="p5v3nv l"></div><div class="p5v3nv r"></div><div class="p5v3mid l"></div><div class="p5v3mid r"></div><div class="p5v3net"></div>'+['A','B'].map(function(t){return[0,1].map(function(k){return'<div class="p5v3p'+cls(t,k)+'" style="'+pos(t,k)+'">'+name(t,k)+ball(t,k)+'</div>'}).join('')}).join('')+'</div>';
 var call=serveTeam==='A'?startA+'–'+startB+'–2':startB+'–'+startA+'–2';
 return shell('<div class="p5v3result">Đội '+serveTeam+' giao trước · '+call+'</div><section class="p5v3card"><h3>Xếp vị trí VĐV</h3><p>Đặt hai VĐV của mỗi đội đúng vị trí thực tế.</p>'+court+'<div class="p5v3legend"><span><i class="p5v3dot s"></i>Giao bóng</span><span><i class="p5v3dot r"></i>Đỡ bóng</span></div><div class="p5v3grid" style="margin-top:12px"><button class="p5v3btn" data-p5="swap'+leftTeam+'">⇅ Đổi VĐV Đội '+leftTeam+'</button><button class="p5v3btn" data-p5="swap'+rightTeam+'">⇅ Đổi VĐV Đội '+rightTeam+'</button></div></section><button class="p5v3primary" data-p5="ready">Sẵn sàng bắt đầu</button>',leftTeam,rightTeam)
}
document.addEventListener('click',function(e){var b=e.target.closest('[data-p5]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();var a=b.dataset.p5;if(a==='back'){app.innerHTML=saved;return}if(a==='toss'){step='pick';return draw()}if(a==='known'){step='known';return draw()}if(a==='pickA'||a==='pickB'){picked=a.slice(-1);return draw()}if(a==='flip'){face=Math.random()<.5?'XANH':'ĐỎ';winner=face==='XANH'?picked:other(picked);chooser=winner;step='result';return draw()}if(a==='knownA'||a==='knownB'){winner=a.slice(-1);chooser=winner;step='result';return draw()}if(['serve','receive','end','defer'].includes(a))return resolve(a);if(a==='left'||a==='right'){endSide=a;return draw()}if(a==='positions'){step='positions';return draw()}if(a==='swapA'||a==='swapB'){order[a.slice(-1)].reverse();return draw()}if(a==='ready'){b.textContent='Đã sẵn sàng';b.disabled=true}},true);
document.addEventListener('click',function(e){var b=e.target.closest('[data-a="saveInfo"]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();Array.from(app.querySelectorAll('[data-player]')).forEach(function(x){x.setAttribute('value',x.value)});saved=app.innerHTML;var ma=saved.match(/aria-label="Điểm bắt đầu Đội A"[^>]*>(\d+)</),mb=saved.match(/aria-label="Điểm bắt đầu Đội B"[^>]*>(\d+)</);startA=ma?+ma[1]:0;startB=mb?+mb[1]:0;step='method';picked=face=winner=chooser=serveTeam=endTeam=deferred='';endSide='left';order={A:[0,1],B:[0,1]};draw()},true)
})();
</script>'''
p.write_text(base+js)
