import {scoreCall} from './match-engine.js';

const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=value=>value?new Date(value).toLocaleString('vi-VN'):'—';
const button=(text,action,cls='ref-button ref-button-primary')=>`<button class="${cls}" data-v1="${escape(action)}">${text}</button>`;
const people=(record,team)=>record.participants.filter(item=>item.team===team).map(item=>escape(item.displayNameAtStart)).join(' / ');
const score=record=>`${record.gamesWon.A} – ${record.gamesWon.B}`;
const statusLabel=value=>({finished:'Đã kết thúc',playing:'Đang diễn ra',gameEnd:'Chờ game tiếp theo',completed:'Đã kết thúc ca',active:'Đang làm việc'}[value]||value);

function matchCard(record){return `<button class="ref-history-card" data-v1="historyMatch:${escape(record.id)}" aria-label="${people(record,'A')} đấu ${people(record,'B')}, kết quả ${score(record)}"><span class="ref-history-line"><b>${people(record,'A')}</b><strong>${record.gamesWon.A}</strong></span><span class="ref-history-line"><b>${people(record,'B')}</b><strong>${record.gamesWon.B}</strong></span><span class="ref-history-meta">${escape(record.context.tournamentName||'Trận nhanh')} · ${escape(record.context.matchLabel)} · ${date(record.matchEndedAt||record.startedAt)} · ${escape(statusLabel(record.status))}</span></button>`}
function tournamentCard(record){return `<button class="ref-history-card" data-v1="historyTournament:${escape(record.id)}"><span class="ref-history-line"><b>${escape(record.name)}</b><strong>${record.matchRecordIds.length}</strong></span><span class="ref-history-meta">${record.workSessionIds.length} ca · ${record.groupRecordIds.length} bảng · ${record.unfinishedObligations.length} việc còn mở · ${date(record.updatedAt)}</span></button>`}
function workCard(record){return `<button class="ref-history-card" data-v1="historyWork:${escape(record.id)}"><span class="ref-history-line"><b>${escape(record.assignment?.label||'Ca làm việc')}</b><strong>${record.matchRecordIds.length}</strong></span><span class="ref-history-meta">${escape(record.tournamentName)} · ${escape(statusLabel(record.status))} · ${date(record.endedAt||record.startedAt)}</span></button>`}
function groupCard(record){const latest=record.snapshots.at(-1);return `<button class="ref-history-card" data-v1="historyGroup:${escape(record.id)}"><span class="ref-history-line"><b>${escape(record.label)}</b><strong>${latest?.status||'—'}</strong></span><span class="ref-history-meta">${record.snapshots.length} snapshot · ${record.completions.length} completion · ${date(record.sortAt)}</span></button>`}

export function historyOverview(projection,results,filters={}){
  const selected=results||[...projection.matches,...projection.tournaments,...projection.workSessions,...projection.groups],by=scope=>selected.filter(item=>item.scope===scope),matches=by('match'),tournaments=by('tournament'),works=by('workSession'),groups=by('group');
  const scope=filters.scope||'all';
  return `<form class="ref-history-search" data-history-search><label>Tìm lịch sử<input name="query" type="search" value="${escape(filters.query||'')}" placeholder="Giải, VĐV, sân, bảng, trận…"></label><label>Phạm vi<select name="scope">${[['all','Tất cả'],['match','Trận'],['tournament','Giải đấu'],['workSession','Ca làm việc'],['group','Bảng']].map(([value,label])=>`<option value="${value}"${scope===value?' selected':''}>${label}</option>`).join('')}</select></label><button class="ref-button ref-button-primary">Tìm</button></form><p class="v1-muted">History là read model từ Match, Tournament, Result, Reporting và Shift ledgers hiện có.</p>${matches.length?`<h2>Kết quả trận</h2>${matches.map(matchCard).join('')}`:''}${tournaments.length?`<h2>Giải đấu</h2>${tournaments.map(tournamentCard).join('')}`:''}${works.length?`<h2>Ca làm việc</h2>${works.map(workCard).join('')}`:''}${groups.length?`<h2>Bảng đấu</h2>${groups.map(groupCard).join('')}`:''}${!selected.length?'<p class="ref-empty">Không tìm thấy record phù hợp.</p>':''}`;
}
const eventRow=event=>`<li><span>${escape(event.label||event.type)}</span><small>${date(event.at)} · ${escape(event.source)}</small>${event.detail?.after?.currentGamePoints?`<small>Game ${event.detail.after.game} · ${event.detail.after.currentGamePoints.A} – ${event.detail.after.currentGamePoints.B} · xướng ${scoreCall(event.detail.after)}</small>`:''}</li>`;
const gameRows=games=>games.map(game=>`<div class="ref-detail-row">Game ${game.gameNumber}<strong>${game.points.A} – ${game.points.B}</strong><small>Đội ${game.winner} thắng</small></div>`).join('');
export function matchRecordDetail(record,{fullTimeline=false}={}){
  const versions=record.canonicalResult.versions,reports=record.reports.versions,timeline=fullTimeline?record.fullTimeline:record.significantEvents;
  return `<section class="ref-detail-result"><p>${escape(record.context.tournamentName||'TRẬN NHANH')} · ${escape(record.context.matchLabel)}</p><h2>${record.winner?`Đội ${record.winner} thắng trận`:'Trận đang diễn ra'}</h2><div class="ref-detail-teams"><span>${people(record,'A')}<b>${record.gamesWon.A}</b></span><span>${people(record,'B')}<b>${record.gamesWon.B}</b></span></div></section><section class="ref-detail-section"><h3>Kết quả hiện hành · game thắng ${score(record)}</h3>${gameRows(record.completedGames)}</section><section class="ref-detail-section"><h3>Danh tính &amp; context</h3>${record.participants.map(person=>`<p><b>${person.team}${person.playerIndex+1} · ${escape(person.displayNameAtStart)}</b><br><small>Player ID: ${escape(person.playerId)} · Entry ID: ${escape(person.entryId)}${person.currentDisplayName!==person.displayNameAtStart?` · Tên hiện tại: ${escape(person.currentDisplayName)}`:''}</small></p>`).join('')}<p>Rules Version: <b>${escape(record.rulesVersion?.label||record.rulesVersionId)}</b> · ${escape(record.rulesVersionId)}<br>Match Start Snapshot: ${escape(record.matchStartSnapshot?.id||'Không áp dụng cho Quick Match')}<br>Bắt đầu: ${date(record.startedAt)}<br>Match End: ${date(record.matchEndedAt)}<br>Result Confirmation: ${date(record.resultConfirmedAt)}</p></section>${versions.length?`<section class="ref-detail-section"><h3>Canonical Result versions</h3>${versions.map(version=>`<article class="ref-history-version"><b>v${version.version} · ${version.isCurrent?'CURRENT':'PREVIOUS'} · ${escape(version.status)}</b><p>Kết quả trận: ${version.matchGamesWon.A} – ${version.matchGamesWon.B}</p>${gameRows(version.completedGames)}<small>${escape(version.source.kind)}${version.source.reason?` · ${escape(version.source.reason)}`:''}</small></article>`).join('')}</section>`:''}<section class="ref-detail-section"><h3>Reports · ${escape(record.reportingStatus)}</h3>${reports.length?reports.map(report=>`<p><b>Revision ${report.revision} · ${escape(report.status)}</b><br><small>Report ${escape(report.id)} · source ${escape(report.source.id)} · Rules ${escape(report.rulesVersionId)}</small></p>`).join(''):'<p>Chưa có report.</p>'}</section><section class="ref-detail-section"><h3>${fullTimeline?'Full Timeline':'Significant Events'} · ${timeline.length}</h3><ol class="ref-event-log">${timeline.map(eventRow).join('')}</ol>${button(fullTimeline?'Chỉ xem Significant Events':'Mở Full Timeline','toggleFullTimeline','ref-button ref-button-secondary')}</section>`;
}
export function tournamentRecordDetail(record,projection){return `<section class="ref-detail-section"><h2>${escape(record.name)}</h2><p>${record.matchRecordIds.length} Match Record · ${record.workSessionIds.length} Work Session · ${record.groupRecordIds.length} Group Record</p><p>Unfinished obligations: <b>${record.unfinishedObligations.length}</b></p></section><section class="ref-detail-section"><h3>Work Sessions</h3>${record.workSessionIds.map(id=>{const work=projection.workSessions.find(item=>item.id===id);return work?button(`${work.assignment?.label||'Ca'} · ${statusLabel(work.status)}`,`historyWork:${id}`,'ref-button ref-button-secondary'):''}).join('')}</section><section class="ref-detail-section"><h3>Matches</h3>${record.matchRecordIds.map(id=>{const match=projection.matches.find(item=>item.id===id);return match?matchCard(match):''}).join('')}</section><section class="ref-detail-section"><h3>Groups</h3>${record.groupRecordIds.map(id=>{const group=projection.groups.find(item=>item.id===id);return group?groupCard(group):''}).join('')}</section>`}
export function workRecordDetail(record,projection){const completion=record.shiftCompletionSnapshot;return `<section class="ref-detail-section"><h2>${escape(record.assignment?.label||'Ca làm việc')}</h2><p>${escape(record.tournamentName)} · ${escape(statusLabel(record.status))}<br>${date(record.startedAt)} → ${date(record.endedAt)}</p><p>Responsibility Scope: ${escape(record.responsibilityScope?.kind)} · ${(record.responsibilityScope?.ids||[]).map(escape).join(', ')}</p></section><section class="ref-detail-section"><h3>Shift Completion Snapshot</h3>${completion?`<p><b>${escape(completion.id)}</b><br>${date(completion.workPeriod.endedAt)} · ${completion.matches.length} match reference · ${completion.outstanding.length} outstanding</p>`:'<p>Chưa kết thúc ca.</p>'}</section><section class="ref-detail-section"><h3>Handover Snapshots</h3>${record.handoverSnapshots.length?record.handoverSnapshots.map(item=>`<p><b>${escape(item.status)} · ${escape(item.id)}</b><br>Người nhận: ${escape(item.recipient.name||'không ghi')} · ${item.outstanding.length} việc dang dở<br><small>HANDED_OVER không đồng nghĩa RESOLVED.</small></p>`).join(''):'<p>Không có handover.</p>'}</section><section class="ref-detail-section"><h3>Current outstanding projection</h3><p>${record.outstanding.outstanding.length} việc · ${record.outstanding.status}</p></section><section class="ref-detail-section"><h3>Matches trong responsibility scope</h3>${record.matchRecordIds.map(id=>{const match=projection.matches.find(item=>item.id===id);return match?matchCard(match):''}).join('')}</section>`}
export function groupRecordDetail(record){return `<section class="ref-detail-section"><h2>${escape(record.label)}</h2><p>Historical snapshots dùng đúng Ranking Rules Version và Result Version IDs đã được đóng dấu; không chạy lại bằng active rules.</p></section>${record.snapshots.map(snapshot=>`<section class="ref-detail-section"><h3>Group Snapshot · ${escape(snapshot.id)}</h3><p>${date(snapshot.createdAt)} · ${escape(snapshot.status)}<br>Ranking Rules: <b>${escape(snapshot.rankingRulesVersion?.label||snapshot.rankingRulesVersionId||'UNKNOWN')}</b> · ${escape(snapshot.rankingRulesVersionId||'UNKNOWN')}<br>Result Versions: ${snapshot.resultVersionIds.map(escape).join(', ')}</p>${snapshot.rows.map(row=>`<p><b>${row.rank??'?'}. ${row.players.map(escape).join(' / ')}</b> · match ${row.matchWins}-${row.matchLosses} · game ${row.gameWins}-${row.gameLosses} · điểm ${row.pointsFor}-${row.pointsAgainst}</p>`).join('')}</section>`).join('')}<section class="ref-detail-section"><h3>Group Completion</h3>${record.completions.map(item=>`<p>${date(item.createdAt)} · <b>${escape(item.status)}</b> · Snapshot ${escape(item.groupSnapshotId||'—')}</p>`).join('')||'<p>Chưa có.</p>'}</section>`}

export function historyList(records){return records.length?records.map(match=>`<button class="ref-history-card" data-v1="record:${escape(match.id)}"><span class="ref-history-line"><b>${match.players.A.map(escape).join(' / ')}</b><strong>${match.gamesWon.A}</strong></span><span class="ref-history-line"><b>${match.players.B.map(escape).join(' / ')}</b><strong>${match.gamesWon.B}</strong></span></button>`).join(''):'<p class="ref-empty">Chưa có trận đã hoàn tất.</p>'}
export function historyDetail(match){return `<section class="ref-detail-result"><h2>Kết quả trận · ${match.gamesWon.A} – ${match.gamesWon.B}</h2></section><section class="ref-detail-section"><h3>Kết quả từng game</h3>${gameRows(match.completedGames)}</section>`}
