import {createTournament,addRulesVersion,addResource,addScheduledMatch,createAssignment,startWorkSession,setMatchReadiness,courtManagerView,matchPlayers} from './tournament-domain.js';
import {callPlayers,requestLoudspeaker,startWaiting,extendWaiting,markPlayersArrived,resolveNoShow,waitingElapsedSeconds,initializePreMatch,confirmAthlete,setEquipmentChecked,startWarmup,finishWarmup,skipWarmup,setPreMatchFinalSetup,createMatchStartSnapshot,stableParticipants} from './tournament-operations.js';
import {launchTournamentMatch,recoverTournamentLaunches} from './tournament-launch.js';
import {createTournamentRepository} from './tournament-persistence.js';
import {createMatchRepository} from './match-persistence.js';
import {addRankingRulesVersion,deriveCanonicalResult,confirmCanonicalResult,correctCanonicalResult,currentResult,calculateGroupSnapshot,assessGroupCompletion} from './tournament-results.js';
import {deriveMatchReport,deriveGroupReport,currentMatchReport,currentGroupReport,reportById,markReportShared,markReportSent,reportingAttention} from './tournament-reporting.js';
import {projectShiftCompletion,createHandoverSnapshot,completeWorkSession,currentShiftCompletion} from './tournament-shift.js';
import './tournament.css';

const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const repo=createTournamentRepository(localStorage),matchRepo=createMatchRepository(localStorage),app=document.getElementById('app');
let screen='',tournamentId=null,workSessionId=null,matchId=null,reportId=null,scopeKind='court',timer=null;
const button=(label,action,secondary=false)=>`<button type="button" class="${secondary?'v1-secondary':'v1-main'}" data-t2="${action}">${label}</button>`;
const field=(label,name,attrs='')=>`<label class="t2-field">${label}<input name="${name}" ${attrs}></label>`;
const option=(values,selected=null)=>values.map(([id,label])=>`<option value="${escape(id)}" ${String(id)===String(selected)?'selected':''}>${escape(label)}</option>`).join('');
const formatTime=value=>value?new Date(value).toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit',second:'2-digit'}):'—';
const duration=seconds=>`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;
function base(title,body,footer=''){
  clearInterval(timer);window.v1Active=true;
  app.innerHTML=`<main class="v1 t2"><header class="v1-head"><button type="button" data-t2="back" aria-label="Quay lại">‹</button><h1>${escape(title)}</h1></header><div class="v1-body">${body}</div>${footer?`<footer class="v1-footer">${footer}</footer>`:''}</main>`;
}
const selected=()=>{const t=repo.get(tournamentId);if(!t)throw Error('Không tìm thấy giải.');return t};
const selectedMatch=t=>{const match=t.schedule.find(item=>item.id===matchId);if(!match)throw Error('Không tìm thấy trận.');return match};
function change(action){try{const t=selected();action(t);repo.save(t);render()}catch(error){alert(error.message)}}

function renderList(){screen='list';const all=repo.list(),active=repo.load().activeWorkSession;
  base('Giải đấu',`<p class="v1-muted">Quản lý luật, lịch trận và phạm vi nhiệm vụ trọng tài.</p>${active?button('TIẾP TỤC NHIỆM VỤ','resume'):''}<h2>Giải của tôi</h2>${all.length?all.map(t=>{const attention=reportingAttention(t);return `<button class="t2-card" data-t2="open:${escape(t.id)}"><b>${escape(t.name)}</b><small>${t.schedule.length} trận · ${t.assignments.length} phân công · ${t.status==='active'?'Đang diễn ra':'Đang chuẩn bị'}${attention.count?` · ${attention.count} biên bản cần xử lý`:''}</small></button>`}).join(''):'<p class="v1-muted">Chưa có giải.</p>'}<form data-t2-form="create">${field('Tên giải','name','required maxlength="100" placeholder="Tên giải"')}<button class="v1-main">Tạo giải</button></form>`,button('Về trang chủ','home',true));
}
function renderTournament(){screen='tournament';const t=selected(),version=t.rulesVersions.find(v=>v.id===t.activeRulesVersionId),ranking=t.rankingRulesVersions?.find(v=>v.id===t.activeRankingRulesVersionId),active=t.workSessions.find(s=>s.status==='active');
  base(t.name,`<section class="t2-section"><h2>Rules Version</h2><p>${version?`${escape(version.label)} · ${escape(version.authority)} · ${version.scoring==='unknown'?'Chưa xác định scoring':escape(version.scoring)} · ${version.format?`${version.format.sets} game / ${version.format.points} điểm`:'Chưa xác định thể thức'} · Dụng cụ: ${escape(version.procedures?.equipmentCheck||'unknown')} · Báo cáo trận/bảng: ${escape(version.procedures?.reporting?.match||'optional')}/${escape(version.procedures?.reporting?.group||'optional')}`:'Chưa xác định phiên bản luật'}</p><form data-t2-form="rules">${field('Tên phiên bản','label','required placeholder="Ví dụ: Luật áp dụng"')}${field('Nguồn luật','authority','required placeholder="Cơ quan và năm phiên bản"')}<label class="t2-field">Scoring<select name="scoring">${option([['unknown','Chưa xác định'],['side-out','Side-out']])}</select></label><div class="t2-grid">${field('Số game','sets','type="number" min="1" max="5" placeholder="1 / 3 / 5"')}${field('Điểm thắng','points','type="number" min="1" max="99" placeholder="11 / 15 / 21…"')}</div><label class="t2-field">Cách thắng<select name="rule">${option([['touch','Chạm điểm'],['unlimited','Cách biệt 2'],['maximum','Maximum cap']])}</select></label>${field('Điểm cap (nếu dùng)','cap','type="number" min="1" max="99"')}<label class="t2-field">Kiểm tra dụng cụ<select name="equipmentCheck">${option([['unknown','Chưa xác định'],['disabled','Không áp dụng'],['optional','Tùy chọn'],['required','Bắt buộc']])}</select></label><label class="t2-field">Biên bản từng trận<select name="matchReporting">${option([['optional','Tùy chọn'],['required','Bắt buộc'],['disabled','Không áp dụng']])}</select></label><label class="t2-field">Biên bản cuối bảng<select name="groupReporting">${option([['optional','Tùy chọn'],['required','Bắt buộc'],['disabled','Không áp dụng']])}</select></label><button class="v1-secondary">Lưu Rules Version</button></form></section>
  <section class="t2-section"><h2>Ranking Rules Version</h2><p>${ranking?`${escape(ranking.label)} · ${escape(ranking.authority)} · ${ranking.criteria.map(item=>escape(item.metric)).join(' → ')||'NEEDS_CONFIRMATION'}`:'Chưa cấu hình — standings sẽ trả NEEDS_CONFIRMATION'}</p><form data-t2-form="rankingRules">${field('Tên phiên bản xếp hạng','label','required placeholder="Ranking Rules áp dụng"')}${field('Nguồn quy định','authority','required placeholder="Ban tổ chức / điều lệ"')}<label class="t2-field">Tiêu chí 1<select name="metric">${option([['','Chưa xác định'],['matchWins','Số trận thắng'],['gameDifferential','Hiệu số game'],['pointDifferential','Hiệu số điểm']])}</select></label>${field('Số suất đi tiếp','qualifierCount','type="number" min="1" placeholder="Để trống nếu chưa xác định"')}<button class="v1-secondary">Lưu Ranking Rules Version</button></form></section>
  <section class="t2-section"><h2>Cấu trúc giải</h2><p>Sân: ${t.structure.courts.length?t.structure.courts.map(x=>escape(x.label)).join(', '):'Chưa xác định'}<br>Bảng: ${t.structure.groups.length?t.structure.groups.map(x=>escape(x.label)).join(', '):'Chưa xác định'}</p><form data-t2-form="resource"><label class="t2-field">Loại<select name="kind">${option([['courts','Sân'],['groups','Bảng']])}</select></label>${field('Tên','label','required placeholder="Tên sân hoặc bảng"')}<button class="v1-secondary">Thêm vào cấu trúc</button></form></section>
  <section class="t2-section"><h2>Lịch trận</h2><p>${t.schedule.length?t.schedule.map(m=>{const players=matchPlayers(t,m);return `${escape(m.label)} · ${m.type==='single'?'Đơn':m.type==='double'?'Đôi':'Chưa rõ'} · ${players?Object.values(players).flat().map(escape).join(' / '):'VĐV chưa xác định'} · ${m.readiness==='unknown'?'Readiness chưa xác định':escape(m.readiness)}`}).join('<br>'):'Chưa có trận.'}</p><form data-t2-form="match">${field('Tên trận','label','required placeholder="Ví dụ: Trận 1"')}<label class="t2-field">Sân<select name="courtId">${option([['','Chưa xác định'],...t.structure.courts.map(c=>[c.id,c.label])])}</select></label><label class="t2-field">Bảng<select name="groupId">${option([['','Chưa xác định'],...t.structure.groups.map(g=>[g.id,g.label])])}</select></label><label class="t2-field">Hình thức<select name="type">${option([['unknown','Chưa xác định'],['single','Đánh đơn'],['double','Đánh đôi']])}</select></label><div class="t2-grid">${field('A1','a1','placeholder="VĐV A1"')}${field('A2 (đôi)','a2','placeholder="VĐV A2"')}${field('B1','b1','placeholder="VĐV B1"')}${field('B2 (đôi)','b2','placeholder="VĐV B2"')}</div><button class="v1-secondary">Thêm trận vào lịch</button></form></section>
  <section class="t2-section"><h2>My Assignment</h2><p>${t.assignments.length?t.assignments.map(a=>`${escape(a.label)} · ${a.scope.kind} · ${a.status}`).join('<br>'):'Chưa có phân công.'}</p><form data-t2-form="assignment">${field('Tên phân công','label','required placeholder="Nhiệm vụ trọng tài"')}<label class="t2-field">Phạm vi<select name="scopeKind" data-t2-scope>${option([['court','Sân'],['group','Bảng'],['match','Trận']],scopeKind)}</select></label><label class="t2-field">Đối tượng<select name="scopeId" required>${option((scopeKind==='court'?t.structure.courts:scopeKind==='group'?t.structure.groups:t.schedule).map(x=>[x.id,x.label]))}</select></label><button class="v1-secondary">Tạo phân công</button></form></section>
  <section class="t2-section"><h2>Nhiệm vụ</h2>${active?button('Tiếp tục nhiệm vụ đang mở',`continue:${active.id}`):t.assignments.filter(a=>a.status==='assigned').map(a=>button(`Bắt đầu · ${escape(a.label)}`,`start:${a.id}`)).join('')||'<p class="v1-muted">Chưa có phân công mới.</p>'}</section>`,button('Danh sách giải','list',true));
}
function operationSummary(match){const o=match.operations;if(!o)return 'Chưa gọi VĐV';const last=o.call.calls.at(-1);if(o.waiting.status==='arrived')return 'VĐV đã đến';if(o.waiting.status==='resolved_no_show')return 'Đã ghi nhận no-show';if(o.waiting.status==='waiting')return `Đang chờ từ ${formatTime(o.waiting.startedAt)}`;return last?`Đã ${last.kind==='recall'?'gọi lại':'gọi'} lúc ${formatTime(last.at)}`:'Chưa gọi VĐV'}
function groupOperations(t,view){const groupIds=[...new Set(view.matches.map(match=>match.groupId).filter(Boolean))];if(!groupIds.length)return '';
  return groupIds.map(groupId=>{const group=t.structure.groups.find(item=>item.id===groupId),snapshot=[...(t.groupSnapshots||[])].reverse().find(item=>item.groupId===groupId),completion=[...(t.groupCompletions||[])].reverse().find(item=>item.groupId===groupId);
    const report=currentGroupReport(t,groupId);return `<section class="t2-section"><h2>${escape(group?.label||'Bảng')} · Standings</h2>${snapshot?`<p>Snapshot ${escape(snapshot.status)} · ${snapshot.resultVersionIds.length} kết quả<br>Rules: ${escape(snapshot.rankingRulesVersionId||'UNKNOWN')}</p>${snapshot.rows.map(row=>`<p><b>${row.rank??'?'}. ${row.players.map(escape).join(' / ')}</b> · ${row.matchWins} trận thắng · game ${row.gameWins}-${row.gameLosses} (HS ${row.gameDifferential}) · điểm ${row.pointsFor}-${row.pointsAgainst} (HS ${row.pointDifferential}) · ${row.qualification}</p>`).join('')}`:'<p class="v1-muted">Chưa có Group Snapshot.</p>'}<p>Group Completion: <b>${escape(completion?.status||'IN_PROGRESS')}</b>${report?`<br>Biên bản: <b>${escape(report.status)}</b> · revision ${report.revision}`:''}</p>${snapshot?button(report?'Mở biên bản bảng':'Tạo biên bản bảng',`reportGroup:${groupId}`,true):''}</section>`}).join('')}
function renderCourt(){screen='court';const t=selected(),v=courtManagerView(t,workSessionId,matchRepo),court=id=>t.structure.courts.find(c=>c.id===id)?.label||'Sân chưa xác định',group=id=>t.structure.groups.find(g=>g.id===id)?.label||'Bảng chưa xác định';
  const attention=v.reportingAttention;base('Court Manager',`<p class="v1-muted">${escape(t.name)} · ${escape(v.assignment.label)} · ${v.assignment.scope.kind==='court'?'Phạm vi sân':v.assignment.scope.kind==='group'?'Phạm vi bảng':'Phạm vi trận'}</p><div class="t2-summary ${attention.status==='HIGH_ATTENTION'?'t2-attention-high':''}"><b>${v.progress.finished}/${v.progress.total} trận hoàn tất · ${v.progress.resultsConfirmed} kết quả đã xác nhận</b><span>${v.progress.ready} sẵn sàng · ${v.progress.unknown} chưa rõ · ${v.progress.blocked} bị chặn${attention.count?` · ${attention.count} biên bản cần xử lý`:''}</span></div><h2>Trận trong nhiệm vụ</h2>${v.matches.length?v.matches.map(m=>{const report=currentMatchReport(t,m.id);return `<article class="t2-section"><h3>${escape(m.label)}</h3><p>${escape(court(m.courtId))} · ${escape(group(m.groupId))}</p><p>Tiến độ: ${m.progress==='not_started'?'Chưa bắt đầu':escape(m.progress)} · ${operationSummary(m)}<br>Readiness: ${m.readiness==='unknown'?'Chưa xác định':m.readiness==='ready'?'Sẵn sàng':'Chưa sẵn sàng'}<br>Kết quả: ${escape(m.resultStatus)}${report?`<br>Biên bản: <b>${escape(report.status)}</b> · revision ${report.revision}`:''}</p>${m.readiness==='blocked'?`<p>${escape(m.blockedReason)}</p>`:''}<div class="t2-actions"><button data-t2="ready:${m.id}">Sẵn sàng</button><button data-t2="unknown:${m.id}">Chưa rõ</button></div>${m.matchSessionId?button(m.progress==='finished'?'Xem / xác nhận kết quả':'Vào Match Session',m.progress==='finished'?`result:${m.id}`:`session:${m.id}`):button(m.operations?.call.calls.length?'Tiếp tục xử lý':'Gọi VĐV',`operations:${m.id}`)}${m.resultStatus==='CONFIRMED'?button(report?'Mở biên bản trận':'Tạo biên bản trận',`reportMatch:${m.id}`,true):''}${!m.matchSessionId?`<form data-t2-form="block:${m.id}">${field('Lý do chưa sẵn sàng','reason','required placeholder="Lý do thực tế"')}<button class="v1-secondary">Đánh dấu bị chặn</button></form>`:''}</article>`}).join(''):'<p class="v1-muted">Chưa có trận thuộc phạm vi này. Lịch trận và phân công được quản lý riêng.</p>'}${groupOperations(t,v)}`,`${button('Kết thúc nhiệm vụ','finish',true)}${button('Về giải','tournament',true)}`);
}

const outstandingAction=entry=>entry.kind==='REQUIRED_MATCH_REPORT'?button('Mở biên bản trận',`reportMatch:${entry.matchId}`,true):entry.kind==='REQUIRED_GROUP_REPORT'?button('Mở biên bản bảng',`reportGroup:${entry.groupId}`,true):'';
function renderShift(){screen=screen==='shiftAttention'?'shiftAttention':'shift';const t=selected(),work=t.workSessions.find(item=>item.id===workSessionId),projection=projectShiftCompletion(t,workSessionId,matchRepo),completion=currentShiftCompletion(t,workSessionId),active=work?.status==='active';
  const rows=projection.outstanding.length?projection.outstanding.map(entry=>`<article class="t2-section"><p><b>${entry.severity==='BLOCKER'?'BLOCKER':'NHẮC VIỆC'}</b> · ${escape(entry.label)}</p>${entry.handedOver?'<p class="v1-muted">Đã ghi nhận trong Handover Snapshot; nghiệp vụ gốc vẫn chưa được đánh dấu resolved.</p>':''}${outstandingAction(entry)}</article>`).join(''):'<section class="t2-section"><h2>Sẵn sàng kết thúc nhiệm vụ</h2><p>Không còn BLOCKER hoặc REMINDER trong phạm vi được giao.</p></section>';
  const handover=active&&projection.outstanding.length&&projection.policy.allowHandover?`<form data-t2-form="handover"><h2>Bàn giao công việc dang dở</h2>${field('Người nhận (tùy chọn)','recipientName','placeholder="Tên người nhận"')}${field('Bối cảnh (tùy chọn)','context','placeholder="Thông tin cần tiếp tục"')}${field('Bóng / dụng cụ (tùy chọn)','equipmentBall','placeholder="Ghi nhận ngắn"')}<button class="v1-secondary">TẠO HANDOVER SNAPSHOT</button></form>`:'';
  const footer=active?`${projection.blockers.length?'':button('XÁC NHẬN KẾT THÚC NHIỆM VỤ','completeShift')}${button('Trở lại Court Manager','court',true)}`:`${button('Về giải','tournament',true)}`;
  base(completion?'Nhiệm vụ đã kết thúc':'Kiểm tra cuối ca',`<p class="v1-muted">${escape(t.name)} · ${escape(t.assignments.find(item=>item.id===work.assignmentId)?.label||'Nhiệm vụ')}</p><div class="t2-summary ${projection.blockers.length?'t2-attention-high':''}"><b>${projection.status}</b><span>${projection.blockers.length} blocker · ${projection.reminders.length} nhắc việc</span></div>${completion?`<section class="t2-section"><h2>Shift Completion Snapshot</h2><p>Kết thúc: ${escape(new Date(completion.workPeriod.endedAt).toLocaleString('vi-VN'))}<br>Snapshot bất biến: ${escape(completion.id)}</p></section>`:''}${rows}${handover}`,footer);
}

function renderResultReview(){screen='result';const t=selected(),match=selectedMatch(t),session=matchRepo.get(match.matchSessionId);if(!session)throw Error('Không tìm thấy Match Session.');let result=currentResult(t,match.id);if(!result){result=deriveCanonicalResult(t,session);repo.save(t)}
  const correction=result.status==='CONFIRMED'?`<section class="t2-section"><h2>Correction có audit</h2><p class="v1-muted">Tạo Result Version mới; phiên bản cũ và reports không bị ghi đè.</p><form data-t2-form="correctResult">${result.completedGames.map((game,index)=>`<div class="t2-grid">${field(`Game ${game.gameNumber} · Đội A`,`gameA${index}`,`required type="number" min="0" max="99" value="${game.points.A}"`)}${field(`Game ${game.gameNumber} · Đội B`,`gameB${index}`,`required type="number" min="0" max="99" value="${game.points.B}"`)}</div>`).join('')}${field('Lý do correction','reason','required placeholder="Quyết định/đối chiếu của BTC"')}<button class="v1-secondary">TẠO RESULT REVISION</button></form></section>`:'';
  base('Xác nhận kết quả',`<p class="v1-muted">${escape(match.label)} · Match kết thúc ${formatTime(result.matchEndedAt)}</p><section class="t2-section"><p>KẾT QUẢ TRẬN · GAME THẮNG</p><h2>${result.players.A.map(escape).join(' / ')} ${result.matchGamesWon.A} – ${result.matchGamesWon.B} ${result.players.B.map(escape).join(' / ')}</h2>${result.completedGames.map(game=>`<p>Game ${game.gameNumber}<b style="float:right">${game.points.A} – ${game.points.B}</b></p>`).join('')}<p>Canonical Result v${result.version} · <b>${escape(result.status)}</b></p><p>Match End Time: ${escape(new Date(result.matchEndedAt).toLocaleString('vi-VN'))}<br>Result Confirmation Time: ${result.confirmedAt?escape(new Date(result.confirmedAt).toLocaleString('vi-VN')):'Chưa xác nhận'}</p></section>${correction}`,result.status==='CONFIRMED'?`${button('Xem biên bản trận',`reportMatch:${match.id}`)}${button('Trở lại Court Manager','court',true)}`:button('XÁC NHẬN KẾT QUẢ','confirmResult'));
}

function renderReport(){screen='report';const t=selected(),report=reportById(t,reportId);if(!report)throw Error('Không tìm thấy biên bản.');
  const work=selected().workSessions.find(item=>item.id===workSessionId),back=work?.status==='completed'?'shiftAttention':'court';
  base('Biên bản',`<p class="v1-muted">Revision ${report.revision} · ${escape(report.status)} · nguồn ${escape(report.source.kind)} ${escape(report.source.id)}</p>${report.attention.severity==='high'?'<p class="t2-alert"><b>CHÚ Ý CAO:</b> Thay đổi ảnh hưởng qualification. Trọng tài phải xem lại trước khi gửi.</p>':''}<section class="t2-section"><h2>${escape(report.artifact.title)}</h2><pre class="t2-report-preview">${escape(report.artifact.body)}</pre><p>Rules Version: ${escape(report.rulesVersionId)}<br>Generated: ${escape(new Date(report.createdAt).toLocaleString('vi-VN'))}${report.sentAt?`<br>Đã gửi BTC: ${escape(new Date(report.sentAt).toLocaleString('vi-VN'))}`:''}</p></section>`,`${report.status!=='SENT'?button('MỞ CHIA SẺ HỆ THỐNG','shareReport'):''}${report.status!=='SENT'?button('ĐÃ GỬI BTC','sentReport',true):''}${button(work?.status==='completed'?'Trở lại việc cần xử lý':'Trở lại Court Manager',back,true)}`);
}
function renderOperations(){screen='operations';const t=selected(),match=selectedMatch(t),o=match.operations,participants=stableParticipants(t,match),calls=o?.call.calls||[],waiting=o?.waiting;
  base('Gọi VĐV / Chờ',`<p class="v1-muted">${escape(match.label)} · ${match.type==='single'?'Đánh đơn':'Đánh đôi'}</p><section class="t2-section"><h2>VĐV</h2><p>${participants.map(p=>`${p.id} · ${escape(p.name)}`).join('<br>')}</p></section><section class="t2-section"><h2>Gọi VĐV</h2><p>${calls.length?calls.map(c=>`${c.kind==='initial'?'Gọi lần đầu':'Gọi lại'} · ${formatTime(c.at)}`).join('<br>'):'Chưa gọi.'}</p>${button(calls.length?'Gọi lại VĐV':'Gọi VĐV','call')}${button('Yêu cầu BTC phát loa','loudspeaker',true)}${o?.call.loudspeakerRequests.length?`<p class="v1-muted">Đã yêu cầu phát loa ${o.call.loudspeakerRequests.length} lần.</p>`:''}</section><section class="t2-section"><h2>Đồng hồ chờ</h2>${waiting?.status==='waiting'?`<div class="t2-wait" data-wait>${duration(waitingElapsedSeconds(match))}</div><p>Bắt đầu chờ lúc ${formatTime(waiting.startedAt)} · Gia hạn ${waiting.extensions.reduce((sum,x)=>sum+x.seconds,0)} giây</p><form data-t2-form="extend">${field('Gia hạn (giây)','seconds','required type="number" min="1" max="3600" value="60"')}${field('Lý do','reason','placeholder="Quyết định của BTC"')}<button class="v1-secondary">Ghi nhận gia hạn</button></form>${button('VĐV đã đến','arrived')}<form data-t2-form="no-show">${field('Quyết định no-show','note','required placeholder="Ghi nhận quyết định của BTC"')}<button class="v1-secondary">Ghi nhận no-show (không tự xử thua)</button></form>`:waiting?.status==='arrived'?`<p><b>VĐV đã đến lúc ${formatTime(waiting.arrivedAt)}</b></p>${button('Vào Pre-Match','prematch')}`:waiting?.status==='resolved_no_show'?`<p><b>Đã ghi nhận no-show</b></p><p>${escape(waiting.resolution.note)}<br>Không tự động xử thua.</p>`:`<p>Thời gian chờ tách biệt với thời điểm gọi.</p>${button('Bắt đầu chờ','startWaiting')}`}</section>`,button('Court Manager','court',true));
  if(waiting?.status==='waiting')timer=setInterval(()=>{const node=app.querySelector('[data-wait]');if(node)node.textContent=duration(waitingElapsedSeconds(selectedMatch(selected())))},500);
}
function renderPreMatch(){screen='prematch';const t=selected(),match=selectedMatch(t),players=matchPlayers(t,match),pre=match.operations?.preMatch,version=t.rulesVersions.find(v=>v.id===t.activeRulesVersionId),participants=stableParticipants(t,match),snapshot=match.matchStartSnapshot,policy=pre?.equipment.policy||version?.procedures?.equipmentCheck||'unknown';
  base('Pre-Match',`<p class="v1-muted">${escape(match.label)} · Rules Version ${escape(version?.label||'chưa xác định')}</p><section class="t2-section"><h2>Xác nhận VĐV</h2>${participants.map(p=>`<button class="t2-check ${pre?.confirmations[p.id]==='confirmed'?'is-done':''}" data-t2="confirm:${p.id}">${p.id} · ${escape(p.name)}<span>${pre?.confirmations[p.id]==='confirmed'?'Đã xác nhận':'Chưa xác nhận'}</span></button>`).join('')}</section><section class="t2-section"><h2>Khởi động</h2><p>Trạng thái: ${pre?.warmup.status||'pending'}</p>${pre?.warmup.status==='pending'?`${button('Bắt đầu 1 phút','warmup')}${button('Bỏ qua','skipWarmup',true)}`:pre?.warmup.status==='active'?button('Hoàn tất khởi động','finishWarmup'):''}</section><section class="t2-section"><h2>Kiểm tra dụng cụ</h2><p>Rules Version: ${escape(policy)}</p>${policy==='unknown'?'<p class="t2-alert">Cần xác định quy định trong Rules Version.</p>':policy==='disabled'?'<p>Không áp dụng.</p>':participants.map(p=>`<button class="t2-check ${pre?.equipment.checks[p.id]?'is-done':''}" data-t2="equipment:${p.id}">${p.id} · ${escape(p.name)}<span>${pre?.equipment.checks[p.id]?'Đã kiểm tra':'Chưa kiểm tra'}</span></button>`).join('')}</section><section class="t2-section"><h2>Final Setup thực tế</h2>${snapshot?`<p><b>Match Start Snapshot đã khóa</b><br>${escape(snapshot.rulesVersion.label)} · ${snapshot.config.start.A}–${snapshot.config.start.B}</p>${button(match.matchSessionId?'Vào Match Session':'BẮT ĐẦU TRẬN','launch')}`:`<form data-t2-form="snapshot"><label class="t2-field">Đội giao đầu tiên<select name="serving">${option([['A','Đội A'],['B','Đội B']])}</select></label><label class="t2-field">Đội ở bên trái trọng tài<select name="courtLeft">${option([['A','Đội A'],['B','Đội B']])}</select></label>${match.type==='double'?`<label class="t2-field">VĐV Đội A ở ô phải<select name="rightA">${option(players.A.map((name,index)=>[index,name]))}</select></label><label class="t2-field">VĐV Đội B ở ô phải<select name="rightB">${option(players.B.map((name,index)=>[index,name]))}</select></label><label class="t2-field">Người giao đầu tiên<select name="serverIndex">${option(players.A.map((name,index)=>[index,`A${index+1} · ${name}`]))}</select></label>`:''}<div class="t2-grid">${field('Điểm đầu Đội A','startA','required type="number" min="0" max="99" value="0"')}${field('Điểm đầu Đội B','startB','required type="number" min="0" max="99" value="0"')}</div><button class="v1-main">Khóa Match Start Snapshot</button></form>`}</section>`,button('Gọi VĐV / Chờ','operations',true));
}
function render(){if(screen==='list')renderList();else if(['tournament','assignment'].includes(screen))renderTournament();else if(screen==='court')renderCourt();else if(screen==='operations')renderOperations();else if(screen==='prematch')renderPreMatch();else if(screen==='result')renderResultReview();else if(screen==='report')renderReport();else if(['shift','shiftAttention'].includes(screen))renderShift()}
export function openTournament(){screen='list';render()}
window.addEventListener('tournament-open',openTournament);
window.addEventListener('application-resume',event=>{
  const target=event.detail;if(target?.kind!=='tournament')return;
  tournamentId=target.tournamentId;workSessionId=target.workSessionId;matchId=target.matchId;
  try{recoverTournamentLaunches(localStorage,tournamentId)}catch(error){alert(error.message);return}
  screen=target.screen;render();
});
window.addEventListener('tournament-return',event=>{const context=event.detail;if(!context)return;tournamentId=context.tournamentId;const loaded=repo.get(tournamentId),active=loaded?.workSessions.find(s=>s.status==='active');if(!active)return openTournament();workSessionId=active.id;screen='court';render()});
window.addEventListener('tournament-result-review',event=>{const context=event.detail;if(!context)return;tournamentId=context.tournamentId;matchId=context.scheduledMatchId;const t=repo.get(tournamentId),active=t?.workSessions.find(item=>item.status==='active');if(!t||!active)return openTournament();workSessionId=active.id;renderResultReview()});
document.addEventListener('change',event=>{
  if(!screen)return;
  if(event.target.matches('[data-t2-scope]')){
    const pendingLabel=app.querySelector('[data-t2-form="assignment"] [name="label"]')?.value||'';
    scopeKind=event.target.value;renderTournament();
    const restored=app.querySelector('[data-t2-form="assignment"] [name="label"]');if(restored)restored.value=pendingLabel;
    return
  }
  if(screen==='prematch'&&event.target.name==='serving'){
    const t=selected(),match=selectedMatch(t),players=matchPlayers(t,match),select=app.querySelector('[name="serverIndex"]');
    if(select)for(const entry of select.options){const index=Number(entry.value),name=players[event.target.value][index];entry.textContent=`${event.target.value}${index+1} · ${name}`}
  }
});
document.addEventListener('submit',event=>{
  const form=event.target.closest('[data-t2-form]');if(!form||!screen)return;event.preventDefault();event.stopImmediatePropagation();
  try{
    const f=new FormData(form),kind=form.dataset.t2Form;
    if(kind==='create'){const t=createTournament(f.get('name'));repo.save(t);tournamentId=t.id;screen='tournament';render();return}
    if(kind==='rules')return change(t=>{const format=f.get('sets')&&f.get('points')?{sets:Number(f.get('sets')),points:Number(f.get('points')),rule:f.get('rule'),cap:Number(f.get('cap'))||undefined}:null;addRulesVersion(t,{label:f.get('label'),authority:f.get('authority'),scoring:f.get('scoring'),format,procedures:{equipmentCheck:f.get('equipmentCheck'),reporting:{match:f.get('matchReporting'),group:f.get('groupReporting')}}})});
    if(kind==='rankingRules')return change(t=>{const metric=f.get('metric'),count=Number(f.get('qualifierCount'));addRankingRulesVersion(t,{label:f.get('label'),authority:f.get('authority'),criteria:metric?[{metric,direction:'desc'}]:[],qualification:count?{kind:'top',count}:{kind:'unknown'}})});
    if(kind==='resource')return change(t=>addResource(t,f.get('kind'),f.get('label')));
    if(kind==='match')return change(t=>{const type=f.get('type'),players=type==='single'?{A:[f.get('a1')],B:[f.get('b1')]}:type==='double'?{A:[f.get('a1'),f.get('a2')],B:[f.get('b1'),f.get('b2')]}:null;addScheduledMatch(t,{label:f.get('label'),courtId:f.get('courtId')||null,groupId:f.get('groupId')||null,type,players})});
    if(kind==='assignment')return change(t=>createAssignment(t,{label:f.get('label'),scopeKind:f.get('scopeKind'),scopeIds:[f.get('scopeId')]}));
    if(kind.startsWith('block:'))return change(t=>setMatchReadiness(t,kind.slice(6),'blocked',f.get('reason')));
    if(kind==='extend')return change(t=>extendWaiting(t,matchId,Number(f.get('seconds')),f.get('reason')));
    if(kind==='no-show')return change(t=>resolveNoShow(t,matchId,f.get('note')));
    if(kind==='correctResult')return change(t=>{const result=currentResult(t,matchId);correctCanonicalResult(t,matchId,{completedGames:result.completedGames.map((game,index)=>({points:{A:Number(f.get(`gameA${index}`)),B:Number(f.get(`gameB${index}`))}})),reason:f.get('reason')})});
    if(kind==='handover')return change(t=>createHandoverSnapshot(t,workSessionId,matchRepo,{recipientName:f.get('recipientName'),context:f.get('context'),equipmentBall:f.get('equipmentBall')}));
    if(kind==='snapshot')return change(t=>{const match=selectedMatch(t),final={serving:f.get('serving'),courtLeft:f.get('courtLeft')};if(match.type==='double'){final.right={A:Number(f.get('rightA')),B:Number(f.get('rightB'))};final.serverIndex=Number(f.get('serverIndex'))}setPreMatchFinalSetup(t,matchId,{start:{A:Number(f.get('startA')),B:Number(f.get('startB'))},final});createMatchStartSnapshot(t,matchId)});
  }catch(error){alert(error.message)}
},true);
document.addEventListener('click',async event=>{
  const b=event.target.closest('[data-t2]');if(!b||!screen)return;event.preventDefault();event.stopImmediatePropagation();const action=b.dataset.t2;
  if(action==='home'){screen='';window.location.reload();return}
  if(action==='back'){if(screen==='prematch')screen='operations';else if(['operations','result'].includes(screen))screen='court';else if(screen==='report')screen=selected().workSessions.find(item=>item.id===workSessionId)?.status==='completed'?'shiftAttention':'court';else if(['shift','shiftAttention'].includes(screen))screen=selected().workSessions.find(item=>item.id===workSessionId)?.status==='active'?'court':'tournament';else if(screen==='court')screen='tournament';else if(screen==='tournament')screen='list';else{screen='';window.location.reload()}render();return}
  if(action==='list'){screen='list';render();return}if(action==='tournament'){screen='tournament';render();return}if(action==='court'){screen='court';render();return}if(action==='operations'){screen='operations';render();return}
  if(action==='resume'){const active=repo.load().activeWorkSession;if(!active)return;tournamentId=active.tournamentId;workSessionId=active.workSessionId;try{recoverTournamentLaunches(localStorage,tournamentId)}catch(error){alert(error.message)}screen='court';render();return}
  if(action.startsWith('open:')){tournamentId=action.slice(5);scopeKind='court';screen='tournament';render();return}
  if(action.startsWith('continue:')){workSessionId=action.slice(9);screen='court';render();return}
  if(action.startsWith('start:')){try{const t=selected(),s=startWorkSession(t,action.slice(6));repo.save(t,{activeWorkSession:s.id});workSessionId=s.id;screen='court';render()}catch(error){alert(error.message)}return}
  if(action==='finish'){screen='shift';render();return}
  if(action==='completeShift'){try{const t=selected();completeWorkSession(t,workSessionId,matchRepo);repo.save(t,{activeWorkSession:null});screen='shift';render()}catch(error){alert(error.message)}return}
  if(action.startsWith('ready:'))return change(t=>setMatchReadiness(t,action.slice(6),'ready'));
  if(action.startsWith('unknown:'))return change(t=>setMatchReadiness(t,action.slice(8),'unknown'));
  if(action.startsWith('operations:')){matchId=action.slice(11);const t=selected();if(!selectedMatch(t).operations){callPlayers(t,matchId);repo.save(t)}screen='operations';render();return}
  if(action==='call')return change(t=>callPlayers(t,matchId));if(action==='loudspeaker')return change(t=>requestLoudspeaker(t,matchId));if(action==='startWaiting')return change(t=>startWaiting(t,matchId));if(action==='arrived')return change(t=>markPlayersArrived(t,matchId));
  if(action==='prematch'){try{const t=selected();initializePreMatch(t,matchId);repo.save(t);screen='prematch';render()}catch(error){alert(error.message)}return}
  if(action.startsWith('confirm:'))return change(t=>{const id=action.slice(8),pre=selectedMatch(t).operations.preMatch;confirmAthlete(t,matchId,id,pre.confirmations[id]!=='confirmed')});
  if(action.startsWith('equipment:'))return change(t=>{const id=action.slice(10),pre=selectedMatch(t).operations.preMatch;setEquipmentChecked(t,matchId,id,!pre.equipment.checks[id])});
  if(action==='warmup')return change(t=>startWarmup(t,matchId,60));if(action==='finishWarmup')return change(t=>finishWarmup(t,matchId));if(action==='skipWarmup')return change(t=>skipWarmup(t,matchId));
  if(action.startsWith('session:')){const match=selected().schedule.find(m=>m.id===action.slice(8)),session=matchRepo.get(match?.matchSessionId);if(session)window.dispatchEvent(new CustomEvent('tournament-match-open',{detail:session}));return}
  if(action.startsWith('result:')){matchId=action.slice(7);return renderResultReview()}
  if(action.startsWith('reportMatch:')){try{const t=selected(),targetId=action.slice(12),result=currentResult(t,targetId);let report=currentMatchReport(t,targetId);if(!report||report.source.id!==result?.id||report.status==='OUTDATED')report=deriveMatchReport(t,targetId,result?.id);repo.save(t);matchId=targetId;reportId=report.id;return renderReport()}catch(error){alert(error.message)}return}
  if(action.startsWith('reportGroup:')){try{const t=selected(),groupId=action.slice(12),snapshot=[...(t.groupSnapshots||[])].reverse().find(item=>item.groupId===groupId);let report=currentGroupReport(t,groupId);if(!report||report.source.id!==snapshot?.id||report.status==='OUTDATED')report=deriveGroupReport(t,groupId,snapshot?.id);repo.save(t);reportId=report.id;return renderReport()}catch(error){alert(error.message)}return}
  if(action==='shareReport'){try{const t=selected(),report=reportById(t,reportId);if(!navigator.share)throw Error('Thiết bị chưa hỗ trợ chia sẻ hệ thống.');await navigator.share(report.artifact.share);markReportShared(t,reportId);repo.save(t);renderReport()}catch(error){if(error.name!=='AbortError')alert(error.message)}return}
  if(action==='sentReport'){try{const t=selected();markReportSent(t,reportId);repo.save(t);renderReport()}catch(error){alert(error.message)}return}
  if(action==='confirmResult'){try{const t=selected(),match=selectedMatch(t),session=matchRepo.get(match.matchSessionId),result=deriveCanonicalResult(t,session),confirmed=confirmCanonicalResult(t,match.id,result.id),rules=t.rulesVersions.find(item=>item.id===(confirmed.rulesVersionId||t.activeRulesVersionId));let snapshot=null,completion=null;if(match.groupId){snapshot=calculateGroupSnapshot(t,match.groupId,t.activeRankingRulesVersionId);completion=assessGroupCompletion(t,match.groupId)}if(rules?.procedures?.reporting?.match==='required')deriveMatchReport(t,match.id,confirmed.id,rules.id);if(rules?.procedures?.reporting?.group==='required'&&completion?.status==='READY')deriveGroupReport(t,match.groupId,snapshot.id,rules.id);repo.save(t);screen='court';render()}catch(error){alert(error.message)}return}
  if(action==='launch'){try{const match=selectedMatch(selected()),session=match.matchSessionId?matchRepo.get(match.matchSessionId):await launchTournamentMatch(tournamentId,workSessionId,matchId,null,localStorage);window.dispatchEvent(new CustomEvent('tournament-match-open',{detail:session}))}catch(error){alert(error.message)}return}
},true);
